# Generated by Django 6.0.4 on 2026-04-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_notification_per_action',
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('notification_type', 'follow'), ('thread__isnull', True)), fields=('sender', 'receiver', 'notification_type'), name='unique_follow_notification'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('notification_type', 'like')), fields=('sender', 'receiver', 'thread', 'notification_type'), name='unique_like_notification'),
        ),
    ]
